export const data = {
    "tracks": {
        "href": "https://api.spotify.com/v1/search?query=tania+bowra&type=track&offset=0&limit=2",
        "items": [
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/08td7MxkoHQkXnWAYD8d6Q"
                            },
                            "href": "https://api.spotify.com/v1/artists/08td7MxkoHQkXnWAYD8d6Q",
                            "id": "08td7MxkoHQkXnWAYD8d6Q",
                            "name": "Tania Bowra",
                            "type": "artist",
                            "uri": "spotify:artist:08td7MxkoHQkXnWAYD8d6Q"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AL",
                        "AR",
                        "AT",
                        "AU",
                        "BA",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "BY",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HR",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "JP",
                        "KW",
                        "KZ",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MK",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "SA",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "UA",
                        "US",
                        "UY",
                        "VN",
                        "XK",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6akEvsycLGftJxYudPjmqK"
                    },
                    "href": "https://api.spotify.com/v1/albums/6akEvsycLGftJxYudPjmqK",
                    "id": "6akEvsycLGftJxYudPjmqK",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b2731ae2bdc1378da1b440e1f610",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e021ae2bdc1378da1b440e1f610",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d000048511ae2bdc1378da1b440e1f610",
                            "width": 64
                        }
                    ],
                    "name": "Place In The Sun",
                    "release_date": "2004-02-02",
                    "release_date_precision": "day",
                    "total_tracks": 11,
                    "type": "album",
                    "uri": "spotify:album:6akEvsycLGftJxYudPjmqK"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/08td7MxkoHQkXnWAYD8d6Q"
                        },
                        "href": "https://api.spotify.com/v1/artists/08td7MxkoHQkXnWAYD8d6Q",
                        "id": "08td7MxkoHQkXnWAYD8d6Q",
                        "name": "Tania Bowra",
                        "type": "artist",
                        "uri": "spotify:artist:08td7MxkoHQkXnWAYD8d6Q"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 240253,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUCR10410004"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/1irrhbi54Uwsrky0s3SrPz"
                },
                "href": "https://api.spotify.com/v1/tracks/1irrhbi54Uwsrky0s3SrPz",
                "id": "1irrhbi54Uwsrky0s3SrPz",
                "is_local": false,
                "name": "Give It 2 Me",
                "popularity": 0,
                "preview_url": "https://p.scdn.co/mp3-preview/83a963732dfed03320b6777d85322fe6113e8e07?cid=de45e40083c44d2181796cf48f0f11ac",
                "track_number": 4,
                "type": "track",
                "uri": "spotify:track:1irrhbi54Uwsrky0s3SrPz"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/08td7MxkoHQkXnWAYD8d6Q"
                            },
                            "href": "https://api.spotify.com/v1/artists/08td7MxkoHQkXnWAYD8d6Q",
                            "id": "08td7MxkoHQkXnWAYD8d6Q",
                            "name": "Tania Bowra",
                            "type": "artist",
                            "uri": "spotify:artist:08td7MxkoHQkXnWAYD8d6Q"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AL",
                        "AR",
                        "AT",
                        "AU",
                        "BA",
                        "BE",
                        "BG",
                        "BH",
                        "BO",
                        "BR",
                        "BY",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HR",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IS",
                        "IT",
                        "JO",
                        "JP",
                        "KW",
                        "KZ",
                        "LB",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MK",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "SA",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SV",
                        "TH",
                        "TN",
                        "TR",
                        "TW",
                        "UA",
                        "US",
                        "UY",
                        "VN",
                        "XK",
                        "ZA"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6akEvsycLGftJxYudPjmqK"
                    },
                    "href": "https://api.spotify.com/v1/albums/6akEvsycLGftJxYudPjmqK",
                    "id": "6akEvsycLGftJxYudPjmqK",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b2731ae2bdc1378da1b440e1f610",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e021ae2bdc1378da1b440e1f610",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d000048511ae2bdc1378da1b440e1f610",
                            "width": 64
                        }
                    ],
                    "name": "Place In The Sun",
                    "release_date": "2004-02-02",
                    "release_date_precision": "day",
                    "total_tracks": 11,
                    "type": "album",
                    "uri": "spotify:album:6akEvsycLGftJxYudPjmqK"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/08td7MxkoHQkXnWAYD8d6Q"
                        },
                        "href": "https://api.spotify.com/v1/artists/08td7MxkoHQkXnWAYD8d6Q",
                        "id": "08td7MxkoHQkXnWAYD8d6Q",
                        "name": "Tania Bowra",
                        "type": "artist",
                        "uri": "spotify:artist:08td7MxkoHQkXnWAYD8d6Q"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "disc_number": 1,
                "duration_ms": 281946,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUCR10410006"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/6UbiYwgZJrwqB5ILDVk1e5"
                },
                "href": "https://api.spotify.com/v1/tracks/6UbiYwgZJrwqB5ILDVk1e5",
                "id": "6UbiYwgZJrwqB5ILDVk1e5",
                "is_local": false,
                "name": "Desire",
                "popularity": 0,
                "preview_url": "https://p.scdn.co/mp3-preview/38131618c20571f2d30d0d7f0faf36fdfa9cb4cf?cid=de45e40083c44d2181796cf48f0f11ac",
                "track_number": 6,
                "type": "track",
                "uri": "spotify:track:6UbiYwgZJrwqB5ILDVk1e5"
            }
        ],
        "limit": 2,
        "next": "https://api.spotify.com/v1/search?query=tania+bowra&type=track&offset=2&limit=2",
        "offset": 0,
        "previous": null,
        "total": 12
    }
}